In [18]:
import numpy as np
import keras

def execute_function(arr1):
  return np.full((3,3),0,np.int32)
  

compare_out = execute_function(np.array(["1","2","3"]))

print(compare_out)






[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [19]:
k = np.array([[[1,2], [3,4]],[[1,2], [3,4]]])

y = np.array([[[1], [2]], [[3],[4]]])

z = k +y
            
print(k.shape, y.shape)

print(z)

print(z.shape)


(2, 2, 2) (2, 2, 1)
[[[2 3]
  [5 6]]

 [[4 5]
  [7 8]]]
(2, 2, 2)


In [25]:
x = np.array([[[1,2], [3,4]]])
y = np.array([[[5],[6]]])
r = keras.layers.Concatenate(axis=-1)([x, y])
print(r.shape)

(1, 2, 3)


In [29]:
print(x.shape, y.shape)
keras.layers.Dot(axes=(2, 1))([x, y])

(1, 2, 2) (1, 2, 1)


<tf.Tensor: shape=(1, 2, 1), dtype=int64, numpy=
array([[[17],
        [39]]])>